[package]
name = "asset-pipeline"
version = "0.1.0"
edition = "2021"

[dependencies]
grass = "0.12.0"
lightningcss = "1.0.0-alpha.65"
rolldown = "0.0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
colored = "2.0"
